In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
d=sns.load_dataset('tips')
d.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [3]:
x=d.iloc[:,2:]

In [4]:
x.head(2)

      sex smoker  day    time  size
0  Female     No  Sun  Dinner     2
1    Male     No  Sun  Dinner     3

In [8]:
x['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

##OneHotEncoding using Pandas

In [10]:
pd.get_dummies(x,columns=['smoker','day'])

,sex,time,size,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun
0,Female,Dinner,2,False,True,False,False,False,True
1,Male,Dinner,3,False,True,False,False,False,True
2,Male,Dinner,3,False,True,False,False,False,True
3,Male,Dinner,2,False,True,False,False,False,True
4,Female,Dinner,4,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...
239,Male,Dinner,3,False,True,False,False,True,False
240,Female,Dinner,2,True,False,False,False,True,False
241,Male,Dinner,2,True,False,False,False,True,False
242,Male,Dinner,2,False,True,False,False,True,False
243,Female,Dinner,2,False,True,True,False,False,False

##. K-1 OneHotEncoding

In [11]:
pd.get_dummies(x,columns=['smoker','day'],drop_first=True)

        sex    time  size  smoker_No  day_Fri  day_Sat  day_Sun
0    Female  Dinner     2       True    False    False     True
1      Male  Dinner     3       True    False    False     True
2      Male  Dinner     3       True    False    False     True
3      Male  Dinner     2       True    False    False     True
4    Female  Dinner     4       True    False    False     True
..      ...     ...   ...        ...      ...      ...      ...
239    Male  Dinner     3       True    False     True    False
240  Female  Dinner     2      False    False     True    False
241    Male  Dinner     2      False    False     True    False
242    Male  Dinner     2       True    False     True    False
243  Female  Dinner     2       True    False    False    False

[244 rows x 7 columns]

##OneHotEncoding using Sklearn

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,x.iloc[:,-1],test_size=0.2,random_state=2)
X_train.head()

        sex smoker   day    time  size
144  Female     No  Thur   Lunch     2
154    Male     No   Sun  Dinner     4
184    Male    Yes   Sun  Dinner     2
161    Male     No   Sun  Dinner     2
44     Male     No   Sun  Dinner     4

In [26]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)
X_train_new = ohe.fit_transform(X_train[['smoker','day','sex']])
X_test_new = ohe.transform(X_test[['smoker','day','sex']])

In [27]:
X_train.shape

(195, 5)

In [28]:
X_train_new.shape

(195, 5)

In [29]:
X_train.head()

        sex smoker   day    time  size
144  Female     No  Thur   Lunch     2
154    Male     No   Sun  Dinner     4
184    Male    Yes   Sun  Dinner     2
161    Male     No   Sun  Dinner     2
44     Male     No   Sun  Dinner     4

In [30]:
X_train_new

array([[0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 1],
       [1, 0, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1],
       [1, 0, 0, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 1, 1],
       [1, 0, 0, 1, 1],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 1, 1],
       [1, 1, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0]], dtype=int32)

In [31]:
ohe.get_feature_names_out()

array(['smoker_Yes', 'day_Sat', 'day_Sun', 'day_Thur', 'sex_Male'],
      dtype=object)

In [32]:
np.hstack((X_train[['time']].values,X_train_new))

array([['Lunch', 0, 0, 0, 1, 0],
       ['Dinner', 0, 0, 1, 0, 1],
       ['Dinner', 1, 0, 1, 0, 1],
       ...,
       ['Dinner', 1, 1, 0, 0, 1],
       ['Dinner', 0, 0, 1, 0, 1],
       ['Dinner', 1, 1, 0, 0, 0]], dtype=object)

##OneHotEncoding with Top Categories

In [34]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [36]:
d1=sns.load_dataset('planets')
d1.head(2)

            method  number  orbital_period  mass  distance  year
0  Radial Velocity       1         269.300  7.10     77.40  2006
1  Radial Velocity       1         874.774  2.21     56.95  2008

In [44]:
c=d1['method'].value_counts()

In [42]:
d1['method'].nunique()
threshold = 5

In [45]:
repl = c[c <= threshold].index

In [46]:
pd.get_dummies(d1['method'].replace(repl, 'uncommon')).sample(5)

,Eclipse Timing Variations,Imaging,Microlensing,Radial Velocity,Transit,uncommon
57,False,False,False,True,False,False
816,False,False,False,False,True,False
335,False,False,False,True,False,False
686,False,False,False,False,True,False
616,False,False,False,True,False,False

In [47]:
!pip install nbformat

Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)