In [248]:
!pip install nbformat

Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)

In [249]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

#column transformation on dataset 1

In [275]:
d1=sns.load_dataset('tips')

In [276]:
d1.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [277]:
from sklearn.compose import ColumnTransformer

In [288]:
d1.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [279]:
d1['sex'].unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [281]:
d1['smoker'].unique()

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [282]:
d1['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [283]:
d1['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [284]:
transformer = ColumnTransformer(transformers=[
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['sex','smoker','day','time'])
],remainder='passthrough')

In [286]:
transformer.fit_transform(d1)

array([[ 0.  ,  0.  ,  0.  , ..., 16.99,  1.01,  2.  ],
       [ 1.  ,  0.  ,  0.  , ..., 10.34,  1.66,  3.  ],
       [ 1.  ,  0.  ,  0.  , ..., 21.01,  3.5 ,  3.  ],
       ...,
       [ 1.  ,  1.  ,  1.  , ..., 22.67,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  , ..., 17.82,  1.75,  2.  ],
       [ 0.  ,  0.  ,  0.  , ..., 18.78,  3.  ,  2.  ]])

#column transformation on dataset 2

In [299]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [304]:
d2=sns.load_dataset('titanic')
d2.head(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

In [305]:
d2.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [310]:
d2['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['First', 'Second', 'Third']

In [ ]:
d2.drop(columns=[''],inplace=True)

In [319]:
t=ColumnTransformer(transformers=[
    ('a',SimpleImputer(),['age']),
    ('b',SimpleImputer(strategy='most_frequent'),['embarked']),
    ('c',SimpleImputer(strategy='constant',fill_value='missing'),['deck']),
    ('d',OrdinalEncoder(categories=[['First', 'Second', 'Third']]),['class']),
    ('e',OneHotEncoder(sparse_output=False,drop='first'),['sex','embarked','alone'])


],remainder='passthrough')

In [321]:
t.fit_transform(d2)

array([[22.0, 'S', 'missing', ..., True, 'Southampton', 'no'],
       [38.0, 'C', 'C', ..., False, 'Cherbourg', 'yes'],
       [26.0, 'S', 'missing', ..., False, 'Southampton', 'yes'],
       ...,
       [29.69911764705882, 'S', 'missing', ..., False, 'Southampton',
        'no'],
       [26.0, 'C', 'C', ..., True, 'Cherbourg', 'yes'],
       [32.0, 'Q', 'missing', ..., True, 'Queenstown', 'no']],
      dtype=object)

In [314]:
t.named_transformers_['b']

SimpleImputer(strategy='most_frequent')

In [315]:

print(t.named_transformers_['b'])

SimpleImputer(strategy='most_frequent')

In [324]:
import pandas as pd

X_transformed = t.fit_transform(d2)
new_df = pd.DataFrame(X_transformed, columns=t.get_feature_names_out())

new_df.head(2)

,a__age,b__embarked,c__deck,d__class,e__sex_male,e__embarked_Q,e__embarked_S,e__embarked_nan,e__alone_True,remainder__survived,remainder__pclass,remainder__sibsp,remainder__parch,remainder__fare,remainder__who,remainder__adult_male,remainder__embark_town,remainder__alive
0,22.0,S,missing,2.0,1.0,0.0,1.0,0.0,0.0,0,3,1,0,7.25,man,True,Southampton,no
1,38.0,C,C,0.0,0.0,0.0,0.0,0.0,0.0,1,1,1,0,71.2833,woman,False,Cherbourg,yes