#original-encoding

In [64]:
import numpy as np
import pandas as pd
import seaborn as sns

In [68]:
d=sns.load_dataset('tips')

In [90]:
d.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [75]:
x=d.iloc[:,2:6]

In [78]:
y=d.iloc[:,-1]

In [87]:
from sklearn.preprocessing import OrdinalEncoder

In [88]:
x['sex'].unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [91]:
x['smoker'].unique()

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [89]:
x['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [92]:
x['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [93]:
oe = OrdinalEncoder(categories=[['Female', 'Male'],['No', 'Yes']
,['Sun', 'Sat', 'Thur', 'Fri'],['Dinner', 'Lunch']

])

In [94]:
oe.fit(x)

OrdinalEncoder(categories=[['Female', 'Male'], ['No', 'Yes'],
                           ['Sun', 'Sat', 'Thur', 'Fri'], ['Dinner', 'Lunch']])

In [98]:
oe.transform(x)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 1., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 1., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 1., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 1., 3., 0.],
       [1., 0., 3., 0.],
       [0., 1., 3., 0.],
       [0., 1., 3., 0.],
       [0., 0., 3., 0.],
       [1., 1., 3., 0.],
       [1., 1., 3., 0.],
       [1., 1., 3., 0.],
       [1., 1., 3., 0.],
       [1., 0., 3., 0.],
       [0., 1., 3., 0.],
       [0., 1., 3., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 1., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [0., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 2., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 2., 1.],
       [1., 1., 2., 1.],
       [1., 1., 2., 1.],
       [1., 1., 2., 1.],
       [1., 0., 2., 1.],
       [1., 1., 2., 1.],
       [0., 1., 2., 1.],
       [0., 1., 2., 1.],
       [1., 1., 2., 1.],
       [1., 1., 2., 1.],
       [0., 1., 2., 1.],
       [0., 1., 2., 1.],
       [0., 1., 2., 1.],
       [1., 1., 2., 1.],
       [0., 1., 2., 1.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 3., 1.],
       [0., 1., 3., 1.],
       [1., 1., 3., 1.],
       [0., 0., 3., 1.],
       [1., 1., 3., 1.],
       [0., 1., 3., 1.],
       [0., 1., 3., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 2., 0.]])

In [99]:
oe.categories_

[array(['Female', 'Male'], dtype=object),
 array(['No', 'Yes'], dtype=object),
 array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object),
 array(['Dinner', 'Lunch'], dtype=object)]

In [104]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(x['sex'])

LabelEncoder()

In [105]:
le.classes_

array(['Female', 'Male'], dtype=object)

In [107]:
x['sex'] = le.transform(x['sex'])

In [108]:
x['sex']

0      0
1      1
2      1
3      1
4      0
      ..
239    1
240    0
241    1
242    1
243    0
Name: sex, Length: 244, dtype: int64

In [109]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(x['day'])

LabelEncoder()

In [112]:
le.classes_
le.transform(x['day'])

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [114]:
!pip install nbformat

Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in /usr/local/lib/python3.12/dist-packages (from nbformat) (5.7.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.5.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from referencing>=0.28.4->jsonschema>=2.6->nbformat) (4.15.0)